
package com.trimax.its.pis.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import model.jaxb.xml.pis.trimax.com.PisResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsPis", targetNamespace = "http://service.pis.its.trimax.com/")
@XmlSeeAlso({
    com.trimax.its.pis.service.ObjectFactory.class,
    model.jaxb.xml.pis.trimax.com.ObjectFactory.class
})
public interface WsPis {


    /**
     * 
     * @param schedualNumber
     * @param busStation
     * @return
     *     returns model.jaxb.xml.pis.trimax.com.PisResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPISData", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISData")
    @ResponseWrapper(localName = "getPISDataResponse", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISDataResponse")
    @Action(input = "http://service.pis.its.trimax.com/wsPis/getPISDataRequest", output = "http://service.pis.its.trimax.com/wsPis/getPISDataResponse")
    public PisResponse getPISData(
        @WebParam(name = "schedual_number", targetNamespace = "")
        String schedualNumber,
        @WebParam(name = "bus_station", targetNamespace = "")
        String busStation);

    /**
     * 
     * @param platformNo
     * @param username
     * @param locationId
     * @param password
     * @return
     *     returns model.jaxb.xml.pis.trimax.com.PisResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPISDetails", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISDetails")
    @ResponseWrapper(localName = "getPISDetailsResponse", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISDetailsResponse")
    @Action(input = "http://service.pis.its.trimax.com/wsPis/getPISDetailsRequest", output = "http://service.pis.its.trimax.com/wsPis/getPISDetailsResponse")
    public PisResponse getPISDetails(
        @WebParam(name = "location_id", targetNamespace = "")
        String locationId,
        @WebParam(name = "platform_no", targetNamespace = "")
        String platformNo,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param getDir
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDir", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetDir")
    @ResponseWrapper(localName = "getDirResponse", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetDirResponse")
    @Action(input = "http://service.pis.its.trimax.com/wsPis/getDirRequest", output = "http://service.pis.its.trimax.com/wsPis/getDirResponse")
    public String getDir(
        @WebParam(name = "getDir", targetNamespace = "")
        String getDir);

    /**
     * 
     * @return
     *     returns model.jaxb.xml.pis.trimax.com.PisResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPISConfiguration", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISConfiguration")
    @ResponseWrapper(localName = "getPISConfigurationResponse", targetNamespace = "http://service.pis.its.trimax.com/", className = "com.trimax.its.pis.service.GetPISConfigurationResponse")
    @Action(input = "http://service.pis.its.trimax.com/wsPis/getPISConfigurationRequest", output = "http://service.pis.its.trimax.com/wsPis/getPISConfigurationResponse")
    public PisResponse getPISConfiguration();

}
