
package com.trimax.its.pis.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsPis", targetNamespace = "http://service.pis.its.trimax.com/", wsdlLocation = "http://10.30.1.154:8080/wsPIS/wsPis?wsdl")
public class WsPis_Service
    extends Service
{

    private final static URL WSPIS_WSDL_LOCATION;
    private final static WebServiceException WSPIS_EXCEPTION;
    private final static QName WSPIS_QNAME = new QName("http://service.pis.its.trimax.com/", "wsPis");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.30.1.154:8080/wsPIS/wsPis?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPIS_WSDL_LOCATION = url;
        WSPIS_EXCEPTION = e;
    }

    public WsPis_Service() {
        super(__getWsdlLocation(), WSPIS_QNAME);
    }

    public WsPis_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPIS_QNAME, features);
    }

    public WsPis_Service(URL wsdlLocation) {
        super(wsdlLocation, WSPIS_QNAME);
    }

    public WsPis_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPIS_QNAME, features);
    }

    public WsPis_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPis_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsPis
     */
    @WebEndpoint(name = "wsPisPort")
    public WsPis getWsPisPort() {
        return super.getPort(new QName("http://service.pis.its.trimax.com/", "wsPisPort"), WsPis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPis
     */
    @WebEndpoint(name = "wsPisPort")
    public WsPis getWsPisPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pis.its.trimax.com/", "wsPisPort"), WsPis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPIS_EXCEPTION!= null) {
            throw WSPIS_EXCEPTION;
        }
        return WSPIS_WSDL_LOCATION;
    }

}
